eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: false
  client:
    enable: true
    register-with-eureka: true
    fetch-registry=false: true
    filter-only-up-instances: true
    register-fetch-interval: 20
    service-url:
      defaultZone: http://localhost:8761/eureka/  #服务注册中心的配置内容，指定服务注册中心的位置